### ISSUE TITLE
Unable to install qpylib as a module due to missing version.py referenced by setup.py

### ISSUE THREAD

**Issue by JPvRiel** [IBM/qpylib#45]
This appears to be most official python wrapper for the QRadar API. However, it cannot be installed as a pip module due to the setup.py having a broken reference: `No such file or directory: 'qpylib/version.py'`

And it is not published to pypi.org.

To reproduce the issue:

```bash
python3 -m venv test
. test/bin/activate
python3 -m pip install git+https://github.com/IBM/qpylib/
```

Output:

```console
Collecting git+https://github.com/IBM/qpylib/
  Cloning https://github.com/IBM/qpylib/ to /tmp/pip-req-build-xu_hxik0
  Running command git clone -q https://github.com/IBM/qpylib/ /tmp/pip-req-build-xu_hxik0
    ERROR: Command errored out with exit status 1:
     command: /home/a211278l/code/threathunt/test/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-xu_hxik0/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-xu_hxik0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-xu_hxik0/pip-egg-info
         cwd: /tmp/pip-req-build-xu_hxik0/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-xu_hxik0/setup.py", line 39, in <module>
        main()
      File "/tmp/pip-req-build-xu_hxik0/setup.py", line 9, in main
        with open("qpylib/version.py", "r") as version_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'qpylib/version.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by mbengit** [comment]
qpylib is currently published only on Github.
https://github.com/IBM/qpylib/blob/master/CONTRIBUTING.md has instructions on how to install a qpylib release.
Releases are available here: https://github.com/IBM/qpylib/releases.
